### ISSUE TITLE
XReslover

### ISSUE THREAD

**Issue by NewAgent2022** [Deputies/CSIPTV#1]
So I See The Code It Trying To Get Gamertag Info But It Will Not Popup The IP Address Location And So On
If You Have Discord Add Me So We Can Talk About It
Discord User: I Am Covid-19#2965

**Comment by Deputies** [comment]
This Isn't An Xbox Related Program But Okay.

**Comment by NewAgent2022** [comment]
I Know That But The XReslover Will Not Popup Any Infomation About The User
